### PR TITLE
Add Motivation Study Guide

### PR DESCRIPTION
**Pull request by JacobK233811**
Add translations to the README-de.md file to include the Motivation and Study Guide sections.

#1 #5

### CODE REVIEW

**Comment by JacobK233811** [comment]
It seems that we both translated Study Guide 😢🤦‍♂️. Would you like me to revert my commit to resolve this conflict? Also, note that when we finish all the sections, we'll need to ensure that section headers and same-page links to those headers are in allignment.

**Comment by JacobK233811** [comment]
Also when looking over the merge conflict, I did not see the In Entwicklung section on the de branch. Are my eyes playing tricks on me?

**Comment by Allaman** [comment]
> It seems that we both translated Study Guide cryman_facepalming. Would you like me to revert my commit to resolve this conflict? Also, note that when we finish all the sections, we'll need to ensure that section headers and same-page links to those headers are in allignment.

That's a pity :( Please revert your commit and if you like check my commit if you find any mistakes. I added a "todo" to check the section headers where appropriate

> Also when looking over the merge conflict, I did not see the In Entwicklung section on the de branch. Are my eyes playing tricks on me?

You are right. I messed something up :( I added the missing stuff and fixed some minor grammar mistakes

Branch "de" should now be fine

**Comment by JacobK233811** [comment]
Yeah, I was a little zoned out from the GitHub context when I did it. I’ve gone and copied my work and yours to a separate location so I can compare for my own betterment too.

I’ll revert the commit. Also, please look over the Motivation section which is also part of this Pull Request and will want to merge.

Glad to see us making good headway.

JacobK233811

**Comment by JacobK233811** [comment]
Handled all conflicts, just needs the once-over review now :+1:

**Comment by JacobK233811** [comment]
Rereading your original comment @Allaman, I see:
> I added the missing stuff and fixed some minor grammar mistakes from your motivation translation

But in the Pull Request, I do not see these changes yet. Did you forget to press the commit button?

**Comment by Allaman** [comment]
I dont get it - my changes are here. Pls compare https://github.com/Allaman/system-design-primer/blob/de/README-de.md#motivation

**Comment by JacobK233811** [comment]
I see, you edited and committed directly to the de branch. As such, I'll close this PR.

**Pull request closed without merging**
